[package]
name = "dessin-pdf"
version = "0.6.13"
edition = "2018"
repository = "https://github.com/daedalus-aero-space/dessin"
license = "MIT"
description = "Dessin to PDF"

[dependencies]
dessin = { version = "0.6.13", path = "../dessin" }
printpdf = { version = "0.4.0", features = ["webp"] }
rusttype = "0.9.2"
