[package]
name = "dessin-pdf"
version = "0.6.16"
edition = "2021"
repository = "https://github.com/daedalus-aero-space/dessin"
license = "MIT"
description = "Dessin to PDF"

[dependencies]
dessin = { version = "0.6.16", path = "../dessin" }
printpdf = { version = "0.4.1", features = ["webp"] }
rusttype = "0.9.2"
