[package]
description = "Dessin to PDF"
edition = "2021"
license = "MIT"
name = "dessin-pdf"
repository = "https://github.com/432-technologies/dessin"
version = "0.8.16-pre"

[dependencies]
dessin = { version = "0.8.16-pre", path = "../dessin" }
fontdue = "^0.8.0"
image = "^0.24.8"
nalgebra = "^0.32.3"
printpdf = { version = "^0.6", features = ["webp", "svg"] }
