[package]
name = "dessin-pdf"
version = "0.8.0"
edition = "2021"
repository = "https://github.com/daedalus-aero-space/dessin"
license = "MIT"
description = "Dessin to PDF"

[dependencies]
dessin = { version = "0.8.0", path = "../dessin" }
printpdf = { git = "https://github.com/fschutt/printpdf", rev = "09958f9", features = [
	"webp",
	"svg",
] }
rusttype = "0.9.3"
