[package]
name = "dessin-pdf"
version = "0.6.4"
edition = "2018"
repository = "https://github.com/daedalus-aero-space/dessin"
license = "MIT"
description = "Dessin to PDF"

[dependencies]
dessin = { version = "0.6.4", path = "../dessin" }
printpdf = "0.4.0"
rusttype = "0.9.2"
