[package]
name = "dessin-pdf"
version = "0.4.11"
edition = "2018"
repository = "https://github.com/daedalus-aero-space/dessin"
license = "MIT"
description = "Dessin to PDF"

[dependencies]
dessin = "0.4.11"
printpdf = "0.4.0"
rusttype = "0.9.2"
