[package]
name = "dessin-pdf"
version = "0.7.0"
edition = "2021"
repository = "https://github.com/daedalus-aero-space/dessin"
license = "MIT"
description = "Dessin to PDF"

[dependencies]
dessin = { version = "0.7.0", path = "../dessin" }
printpdf = { version = "0.5.2", features = ["webp", "svg"] }
rusttype = "0.9.2"
