[package]
name = "dessin-pdf"
version = "0.8.0-pre"
edition = "2021"
repository = "https://github.com/432-technologies/dessin"
license = "MIT"
description = "Dessin to PDF"

[dependencies]
dessin = { version = "0.8.0-pre", path = "../dessin" }
printpdf = { git = "https://github.com/fschutt/printpdf", rev = "e78b284", features = [
	"webp",
	"svg",
] }
fontdue = "^0.7.2"
image = "^0.24.5"
nalgebra = "^0.32.0"
once_cell = "1.17.1"
