[package]
name = "dessin"
version = "0.2.0"
authors = ["Olivier Lemoine <olivier@le-moine.fr>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/daedalus-aero-space/drawing"
description = "Build complex drawing for PDF, SVG, ..."

[dependencies]
algebr = "0.1.0"
