[package]
name = "drawing"
version = "0.1.0"
authors = ["Olivier Lemoine <olivier@le-moine.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algebra = { git = "https://github.com/daedalus-aero-space/algebra", branch = "main" }
