[package]
name = "dessin"
version = "0.2.5"
authors = ["Olivier Lemoine <olivier@le-moine.fr>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/daedalus-aero-space/dessin"
description = "Build complex drawing for PDF, SVG, ..."

[dependencies]
algebr = "0.1"
