[package]
name = "dessin-iced"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
authors.workspace = true

[dependencies]
dessin = { version = "^0.8.23", path = "../dessin" }
iced_core = { git = "https://github.com/432-Technologies/iced",rev="16cacc8" , default-features = false }
iced_widget = { git = "https://github.com/432-Technologies/iced",rev="16cacc8" , default-features = false, features = ["canvas", "image"] }
iced_graphics = { git = "https://github.com/432-Technologies/iced",rev="16cacc8" , default-features = false, features = ["image"] }
tracing = "0.1"
