[package]
name = "dessin-iced"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
authors.workspace = true

[dependencies]
dessin = { version = "^0.8.23", path = "../dessin" }
iced_core = { path = "../../iced/core", default-features = false }
iced_widget = { path = "../../iced/widget", default-features = false, features = ["canvas", "image"] }
iced_graphics = { path = "../../iced/graphics", default-features = false, features = ["image"] }
tracing = "0.1"
