[package]
name = "dessin"
version = "0.8.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/daedalus-aero-space/dessin"
description = "Build complex drawing for PDF, SVG, ..."

[dependencies]
fontdue = "^0.7.2"
image = "^0.24.5"
nalgebra = "^0.32.2"
