[package]
name = "dessin"
version = "0.8.4-pre"
edition = "2021"
license = "MIT"
repository = "https://github.com/432-technologies/dessin"
description = "Build complex drawing for PDF, SVG, ..."

[dependencies]
fontdue = "^0.7.3"
image = "^0.24.6"
nalgebra = "^0.32.2"
once_cell = "^1.17.1"
palette = "^0.7.1"
dessin-macros = { path = "dessin-macros", version = "0.8.4-pre" }
