[package]
name = "dessin"
version = "0.8.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/daedalus-aero-space/dessin"
description = "Build complex drawing for PDF, SVG, ..."

[dependencies]
image = "0.24.5"
nalgebra = "0.32.2"
rusttype = "0.9.3"
