[package]
name = "dessin"
version = "0.7.3"
edition = "2021"
license = "MIT"
repository = "https://github.com/daedalus-aero-space/dessin"
description = "Build complex drawing for PDF, SVG, ..."

[dependencies]
algebr = "0.1"
rusttype = "0.9.3"
