[package]
name = "dessin"
version = "0.6.2"
edition = "2018"
license = "MIT"
repository = "https://github.com/daedalus-aero-space/dessin"
description = "Build complex drawing for PDF, SVG, ..."

[dependencies]
algebr = "0.1"
