[package]
name = "dessin"
version = "0.8.0-pre"
edition = "2021"
license = "MIT"
repository = "https://github.com/432-technologies/dessin"
description = "Build complex drawing for PDF, SVG, ..."

[dependencies]
fontdue = "^0.7.2"
image = "^0.24.5"
nalgebra = "^0.32.0"
once_cell = "1.17.1"
palette = "^0.6.1"
