[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"

[dev-dependencies]
dessin = { path = "../dessin" }
dessin-svg = { path = "../dessin-svg" }
dessin-image = { path = "../dessin-image" }
dessin-pdf = { path = "../dessin-pdf" }
dessin-iced = { path = "../dessin-iced" }
project-root = "0.2.2"
palette = "0.7.6"
iced = { git = "https://github.com/OlivierLemoine/iced.git", rev = "05f161b" }

[[example]]
name = "any-triangle"
path = "./any-triangle.rs"

[[example]]
name = "croix-basque"
path = "./croix-basque.rs"

[[example]]
name = "logo-432technologies"
path = "./logo-432technologies.rs"

[[example]]
name = "font"
path = "./font.rs"

[[example]]
name = "optical-effect"
path = "./optical-effect.rs"

[[example]]
name = "text-bb"
path = "./text-bb.rs"

[[example]]
name = "text-rotation"
path = "./text-rotation.rs"

[[example]]
name = "textbox"
path = "./textbox.rs"
